require('plugins')
require('keybindings')
require('treesitter-config')
require('lualine-config')
require('options')
require('bufferline-config')
require('nvimtree-config')
require('autopairs-config')
require('whichkey-config')
vim.cmd('colorscheme catppuccin-mocha')

